taskName: Default Task
taskDescription: Optimization of a set of individual chemical elements for a large set ot High Entropy Alloys from ULTERA database
datasetPath: dataList.txt
elementOrder:
- Fe
- Cr
- Ni
- Co
- Al
- Ti
- Nb
- Cu
- Mo
- Ta
- Zr
- V
- Hf
- W
- Mn
- Si
- Re
- B
- Ru
- C
- Sn
- Mg
- Zn
- Li
- O
- Y
- Pd
- N
- Ca
- Ir
- Sc
- Ge
- Be
- Ag
- Nd
- S
- Ga
