name: Generate Documentation

on:
  push:
    paths:
      - nimcso/**
      - .github/workflows/draft-pdf.yml

jobs:
  generateDocumentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build documentation
        run: nim doc --project --index:on --outdir:docs  nimcso/nimcso
      - name: Commit documentation to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Documentation'
          add: 'docs/**'