name: Draft PDF
on:
  push:
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml
    tags-ignore:
        - '**'
  workflow_dispatch:
    
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf

      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          add: 'paper/*.pdf'
          push: origin HEAD:main
