name: MacOS Tests (M1)

on:
  push:
    paths:
      - 'tests/**'
      - 'src/**'
      - '.github/workflows/testingOnPush_Apple.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nim with Homebrew
        run: brew install nim

      - name: Install nimCSO (and dependencies)
        run: nimble install -y
        
      - name: Compile minCSO
        run: nim c -d:release src/nimcso

      - name: Runtime all tests under release mode
        run: nim c -r -f -d:release -d:configPath=tests/config.yaml tests/runAll
        
      - name: Runtime all tests under danger mode
        run: nim c -r -f -d:danger -d:configPath=tests/config.yaml tests/runAll