name: Linux (Ubuntu) Tests

on:
  push:
    paths:
      - 'tests/**'
      - 'src/**'
      - '.github/workflows/testingOnPush_Linux.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.2'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nimCSO (and dependencies)
        run: nimble install -y

      - name: Compile minCSO
        run: nim c -d:release src/nimcso

      - name: Runtime tests of benchmarks under release mode
        run: nim c -r -f -d:release -d:configPath=tests/config.yaml tests/benchmarksRuntime
      - name: Runtime tests of benchmarks under danger mode
        run: nim c -r -f -d:danger -d:configPath=tests/config.yaml tests/benchmarksRuntime

      - name: Brute Force under release mode (has to work)
        run: nim c -r -f -d:release -d:configPath=tests/config.yaml tests/bruteForce
      - name: Brute Force under danger mode (should work)
        run: nim c -r -f -d:danger -d:configPath=tests/config.yaml tests/bruteForce
        
      - name: Least Preventing / Most Common under release mode (has to work)
        run: nim c -r -f -d:release -d:configPath=tests/config.yaml tests/leastPreventing
      - name: Least Preventing / Most Common under danger mode (should work)
        run: nim c -r -f -d:danger -d:configPath=tests/config.yaml tests/leastPreventing

      - name: Algorithm Search under release mode (has to work)
        run: nim c -r -f -d:release -d:configPath=tests/config.yaml tests/algorithmSearch
      - name: Algorithm Search under danger mode (should work)
        run: nim c -r -f -d:danger -d:configPath=tests/config.yaml tests/algorithmSearch