name: Linux (Ubuntu) Tests

on:
  push:
    paths:
      - 'tests/**'
      - 'src/**'
      - '.github/workflows/testingOnPush_Linux.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim:
          - '1.4.x'
          - '1.6.x'
          - '2.0.0'
          - '2.0.x'
          - 'stable'
    name: Nim ${{ matrix.nim }} Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nimCSO (and dependencies)
        run: nimble install -y

      - name: Compile minCSO
        run: nim c -d:release src/nimcso

      - name: Runtime all tests under release mode
        run: nim c -r -f -d:release -d:configPath=tests/config.yaml tests/runAll
        
      - name: Runtime all tests under danger mode
        run: nim c -r -f -d:danger -d:configPath=tests/config.yaml tests/runAll